use crate::fiero::Fiero;
use Fiero::*;

pub fn to_syllabics(fiero: &[Fiero]) -> String {
    let mut acc = String::new();
    let mut rem = fiero;
    while !rem.is_empty() {
        if rem.len() >= 3 {
            let c = triple_syllabic(rem[0], rem[1], rem[2]);
            if !c.is_empty() {
                acc.push_str(c);
                rem = &rem[3..];
                continue;
            }
        }
        if rem.len() >= 2 {
            let c = double_syllabic(rem[0], rem[1]);
            if !c.is_empty() {
                acc.push_str(c);
                rem = &rem[2..];
                continue;
            }
        }
        acc.push_str(single_syllabic(rem[0]));
        rem = &rem[1..];
    }
    acc
}

fn single_syllabic(x: Fiero) -> &'static str {
    match x {
        E => "ᐁ",
        II => "ᐄ",
        I => "ᐃ",
        OO => "ᐆ",
        O => "ᐅ",
        AA => "ᐋ",
        A => "ᐊ",
        W => "ᐤ",
        H => "ᐦ",

        P => "ᑊ",
        B => "ᑊ",
        TH => "ᕪ",
        T => "ᐟ",
        D => "ᐟ",
        K => "ᐠ",
        G => "ᐠ",
        CH => "ᐨ",
        J => "ᐨ",
        M => "ᒼ",
        N => "ᐣ",
        SH => "ᐡ",
        ZH => "ᐡ",
        S => "ᐢ",
        Z => "ᐢ",
        Y => "ᔾ",
        FV => "ᕝ",
        R => "ᕑ",
        L => "ᓫ",

        SPACE => " ",
        DASH => "᐀",
    }
}

fn double_syllabic(c: Fiero, v: Fiero) -> &'static str{
    match (c,v){
        (W, E) => "ᐍ",
        (W, II) => "ᐑ",
        (W, I) => "ᐏ",
        (W, OO) => "ᐕ",
        (W, O) => "ᐓ",
        (W, AA) => "ᐚ",
        (W, A) => "ᐘ",
        (P, E) => "ᐯ",
        (P, II) => "ᐲ",
        (P, I) => "ᐱ",
        (P, OO) => "ᐴ",
        (P, O) => "ᐳ",
        (P, AA) => "ᐹ",
        (P, A) => "ᐸ",
        (B, E) => "ᐯ",
        (B, II) => "ᐲ",
        (B, I) => "ᐱ",
        (B, OO) => "ᐴ",
        (B, O) => "ᐳ",
        (B, AA) => "ᐹ",
        (B, A) => "ᐸ",
        (TH, E) => "ᕞ",
        (TH, II) => "ᕢ",
        (TH, I) => "ᕠ",
        (TH, OO) => "ᕥ",
        (TH, O) => "ᕤ",
        (TH, AA) => "ᕧ",
        (TH, A) => "ᕦ",
        (T, E) => "ᑌ",
        (T, II) => "ᑏ",
        (T, I) => "ᑎ",
        (T, OO) => "ᑑ",
        (T, O) => "ᑐ",
        (T, AA) => "ᑖ",
        (T, A) => "ᑕ",
        (D, E) => "ᑌ",
        (D, II) => "ᑏ",
        (D, I) => "ᑎ",
        (D, OO) => "ᑑ",
        (D, O) => "ᑐ",
        (D, AA) => "ᑖ",
        (D, A) => "ᑕ",
        (K, E) => "ᑫ",
        (K, II) => "ᑮ",
        (K, I) => "ᑭ",
        (K, OO) => "ᑰ",
        (K, O) => "ᑯ",
        (K, AA) => "ᑳ",
        (K, A) => "ᑲ",
        (G, E) => "ᑫ",
        (G, II) => "ᑮ",
        (G, I) => "ᑭ",
        (G, OO) => "ᑰ",
        (G, O) => "ᑯ",
        (G, AA) => "ᑳ",
        (G, A) => "ᑲ",
        (CH, E) => "ᒉ",
        (CH, II) => "ᒌ",
        (CH, I) => "ᒋ",
        (CH, OO) => "ᒎ",
        (CH, O) => "ᒍ",
        (CH, AA) => "ᒑ",
        (CH, A) => "ᒐ",
        (J, E) => "ᒉ",
        (J, II) => "ᒌ",
        (J, I) => "ᒋ",
        (J, OO) => "ᒎ",
        (J, O) => "ᒍ",
        (J, AA) => "ᒑ",
        (J, A) => "ᒐ",
        (M, E) => "ᒣ",
        (M, II) => "ᒦ",
        (M, I) => "ᒥ",
        (M, OO) => "ᒨ",
        (M, O) => "ᒧ",
        (M, AA) => "ᒫ",
        (M, A) => "ᒪ",
        (N, E) => "ᓀ",
        (N, II) => "ᓃ",
        (N, I) => "ᓂ",
        (N, OO) => "ᓅ",
        (N, O) => "ᓄ",
        (N, AA) => "ᓈ",
        (N, A) => "ᓇ",
        (SH, E) => "ᔐ",
        (SH, II) => "ᔒ",
        (SH, I) => "ᔑ",
        (SH, OO) => "ᔔ",
        (SH, O) => "ᔓ",
        (SH, AA) => "ᔖ",
        (SH, A) => "ᔕ",
        (ZH, E) => "ᔐ",
        (ZH, II) => "ᔒ",
        (ZH, I) => "ᔑ",
        (ZH, OO) => "ᔔ",
        (ZH, O) => "ᔓ",
        (ZH, AA) => "ᔖ",
        (ZH, A) => "ᔕ",
        (S, E) => "ᓭ",
        (S, II) => "ᓰ",
        (S, I) => "ᓯ",
        (S, OO) => "ᓲ",
        (S, O) => "ᓱ",
        (S, AA) => "ᓵ",
        (S, A) => "ᓴ",
        (Z, II) => "ᓰ",
        (Z, I) => "ᓯ",
        (Z, OO) => "ᓲ",
        (Z, O) => "ᓱ",
        (Z, AA) => "ᓵ",
        (Z, A) => "ᓴ",
        (Y, E) => "ᔦ",
        (Y, II) => "ᔩ",
        (Y, I) => "ᔨ",
        (Y, OO) => "ᔫ",
        (Y, O) => "ᔪ",
        (Y, AA) => "ᔮ",
        (Y, A) => "ᔭ",
        (FV, E) => "ᕓ",
        (FV, II) => "ᕖ",
        (FV, I) => "ᕕ",
        (FV, OO) => "ᕘ",
        (FV, O) => "ᕗ",
        (FV, AA) => "ᕚ",
        (FV, A) => "ᕙ",
        (R, E) => "ᕃ",
        (R, II) => "ᕇ",
        (R, I) => "ᕆ",
        (R, OO) => "ᕉ",
        (R, O) => "ᕈ",
        (R, AA) => "ᕌ",
        (R, A) => "ᕋ",
        (L, E) => "ᓓ",
        (L, II) => "ᓖ",
        (L, I) => "ᓕ",
        (L, OO) => "ᓘ",
        (L, O) => "ᓗ",
        (L, AA) => "ᓛ",
        (L, A) => "ᓚ",
        _ => "",
    }
}

fn triple_syllabic(c: Fiero, w: Fiero, v: Fiero) -> &'static str{
    match (c,w,v){
        (P, W, E) => "ᐻ",
        (P, W, II) => "ᐿ",
        (P, W, I) => "ᐽ",
        (P, W, OO) => "ᑃ",
        (P, W, O) => "ᑁ",
        (P, W, AA) => "ᑇ",
        (P, W, A) => "ᑅ",
        (B, W, E) => "ᐻ",
        (B, W, II) => "ᐿ",
        (B, W, I) => "ᐽ",
        (B, W, OO) => "ᑃ",
        (B, W, O) => "ᑁ",
        (B, W, AA) => "ᑇ",
        (B, W, A) => "ᑅ",
        (TH, W, E) => "ᣣ",
        (TH, W, AA) => "ᕩ",
        (TH, W, A) => "ᣤ",
        (T, W, E) => "ᑘ",
        (T, W, II) => "ᑜ",
        (T, W, I) => "ᑜ",
        (T, W, OO) => "ᑠ",
        (T, W, O) => "ᑞ",
        (T, W, AA) => "ᑤ",
        (T, W, A) => "ᑢ",
        (D, W, E) => "ᑘ",
        (D, W, II) => "ᑜ",
        (D, W, I) => "ᑜ",
        (D, W, OO) => "ᑠ",
        (D, W, O) => "ᑞ",
        (D, W, AA) => "ᑤ",
        (D, W, A) => "ᑢ",
        (K, W, E) => "ᑵ",
        (K, W, II) => "ᑹ",
        (K, W, I) => "ᑷ",
        (K, W, OO) => "ᑽ",
        (K, W, O) => "ᑻ",
        (K, W, AA) => "ᒁ",
        (K, W, A) => "ᑿ",
        (G, W, E) => "ᑵ",
        (G, W, II) => "ᑹ",
        (G, W, I) => "ᑷ",
        (G, W, OO) => "ᑽ",
        (G, W, O) => "ᑻ",
        (G, W, AA) => "ᒁ",
        (G, W, A) => "ᑿ",
        (CH, W, E) => "ᒓ",
        (CH, W, II) => "ᒗ",
        (CH, W, I) => "ᒕ",
        (CH, W, OO) => "ᒛ",
        (CH, W, O) => "ᒙ",
        (CH, W, AA) => "ᒟ",
        (CH, W, A) => "ᒝ",
        (J, W, E) => "ᒓ",
        (J, W, II) => "ᒗ",
        (J, W, I) => "ᒕ",
        (J, W, OO) => "ᒛ",
        (J, W, O) => "ᒙ",
        (J, W, AA) => "ᒟ",
        (J, W, A) => "ᒝ",
        (M, W, E) => "ᒭ",
        (M, W, II) => "ᒱ",
        (M, W, I) => "ᒯ",
        (M, W, OO) => "ᒵ",
        (M, W, O) => "ᒳ",
        (M, W, AA) => "ᒹ",
        (M, W, A) => "ᒷ",
        (N, W, E) => "ᓊ",
        (N, W, II) => "ᣉ",
        (N, W, I) => "ᣇ",
        (N, W, OO) => "ᣍ",
        (N, W, O) => "ᣋ",
        (N, W, AA) => "ᓎ",
        (N, W, A) => "ᓌ",
        (SH, W, E) => "ᔘ",
        (SH, W, II) => "ᔜ",
        (SH, W, I) => "ᔚ",
        (SH, W, OO) => "ᔠ",
        (SH, W, O) => "ᔞ",
        (SH, W, AA) => "ᔤ",
        (SH, W, A) => "ᔢ",
        (ZH, W, E) => "ᔘ",
        (ZH, W, II) => "ᔜ",
        (ZH, W, I) => "ᔚ",
        (ZH, W, OO) => "ᔠ",
        (ZH, W, O) => "ᔞ",
        (ZH, W, AA) => "ᔤ",
        (ZH, W, A) => "ᔢ",
        (S, W, E) => "ᓷ",
        (S, W, II) => "ᓻ",
        (S, W, I) => "ᓹ",
        (S, W, OO) => "ᓿ",
        (S, W, O) => "ᓽ",
        (S, W, AA) => "ᔃ",
        (S, W, A) => "ᔁ",
        (Z, W, E) => "ᓷ",
        (Z, W, II) => "ᓻ",
        (Z, W, I) => "ᓹ",
        (Z, W, OO) => "ᓿ",
        (Z, W, O) => "ᓽ",
        (Z, W, AA) => "ᔃ",
        (Z, W, A) => "ᔁ",
        (Y, W, E) => "ᔰ",
        (Y, W, II) => "ᔴ",
        (Y, W, I) => "ᔲ",
        (Y, W, OO) => "ᔫ",
        (Y, W, O) => "ᔪ",
        (Y, W, AA) => "ᔼ",
        (Y, W, A) => "ᔺ",
        (R, W, AA) => "ᕏ",
        (L, W, E) => "ᓝ",
        (L, W, II) => "ᓡ",
        (L, W, I) => "ᓟ",
        (L, W, OO) => "ᓥ",
        (L, W, O) => "ᓣ",
        (L, W, AA) => "ᓩ",
        (L, W, A) => "ᓧ",
        _ => "",
    }
}




